export const ANIME_SERIES_TITLE_ZH: Record<string, string> = {
  "A Certain Magical Index": "魔法禁書目錄",
  "A Silent Voice": "聲之形",
  "Accel World": "加速世界",
  "Air Gear": "飛輪少年",
  "Akame Ga Kill": "斬！赤紅之瞳",
  "Akame ga Kill!": "斬！赤紅之瞳",
  "Amagi Brilliant Park": "甘城輝煌樂園救世主",
  "Angel Beats!": "天使的脈動",
  Another: "替身",
  "Attack on Titan": "進擊的巨人",
  "Baka and Test: Summon the Beasts": "笨蛋，測驗，召喚獸",
  "Baka and Test:Summon the Beasts": "笨蛋，測驗，召喚獸",
  Bakemonogatari: "化物語",
  "Bakemonogatari, Monogatari Series": "化物語／物語系列",
  Beelzebub: "惡魔奶爸",
  "Beyond the Boundary": "境界的彼方",
  "Black Bullet": "黑色子彈",
  "Black Butler": "黑執事",
  "Black Clover": "黑色五葉草",
  "Black Lagoon": "企業傭兵",
  "Blade Dance of the Elementalers": "精靈使的劍舞",
  Bleach: "死神",
  "Blue Exorcist": "青之驅魔師",
  "Cardcaptor Sakura": "庫洛魔法使",
  "Chainsaw Man": "鏈鋸人",
  Chobits: "人形電腦天使心",
  Claymore: "大劍",
  "Code Geass": "反叛的魯路修",
  "Code Geass: Lelouch of the Rebellion": "反叛的魯路修",
  "Cowboy Bebop": "星際牛仔",
  "Cross Ange: Rondo of Angel and Dragon": "天使與龍的輪舞",
  "Date A Live": "約會大作戰",
  "Deadman Wonderland": "死囚樂園",
  "Death Note": "死亡筆記",
  "Death Parade": "死亡遊行",
  "Demon Slayer: Kimetsu no Yaiba": "鬼滅之刃",
  "Dragon Ball Z": "七龍珠 Z",
  "Durarara!!": "無頭騎士異聞錄",
  "Elfen Lied": "妖精的旋律",
  "Fairy Tail": "魔導少年",
  "Fate/Stay Night": "命運／停駐之夜",
  "Fate/Zero": "命運／零話",
  "Food Wars! Shokugeki no Soma": "食戟之靈",
  "Fruits Basket": "魔法水果籃",
  "Full Metal Panic!": "驚爆危機",
  "Fullmetal Alchemist": "鋼之鍊金術師",
  "Future Diary": "未來日記",
  "Ghost in the Shell": "攻殼機動隊",
  Gintama: "銀魂",
  "Golden Time": "青春紀行",
  "Ground Control to Psychoelectric Girl": "電波女與青春男",
  "Guilty Crown": "罪惡王冠",
  "Gurren Lagann": "天元突破 紅蓮螺巖",
  Haganai: "我的朋友很少",
  "Hayate the Combat Butler": "旋風管家",
  "Heaven's Lost Property": "天降之物",
  Hellsing: "皇家國教騎士團",
  "High School DxD": "惡魔高校 D×D",
  "Highschool of the Dead": "學園默示錄",
  "Himouto! Umaru-chan": "乾物妹！小埋",
  "Howl's Moving Castle": "霍爾的移動城堡",
  "Infinite Stratos": "無限斯特拉托斯",
  "Inu x Boku SS": "妖狐×僕SS",
  InuYasha: "犬夜叉",
  Inuyasha: "犬夜叉",
  "Is This a Zombie?": "這樣算是殭屍嗎？",
  "JoJo's Bizarre Adventure": "喬喬的奇妙冒險",
  "Jujutsu Kaisen": "咒術迴戰",
  "K-ON!": "輕音部",
  "K-On!": "輕音部",
  "Kaguya-sama: Love is War": "輝夜姬想讓人告白",
  Kakegurui: "狂賭之淵",
  "Kamisama Kiss": "元氣少女緣結神",
  "Kiki's Delivery Service": "魔女宅急便",
  "Kill la Kill": "斬服少女",
  "Kimi ni Todoke": "好想告訴你",
  "Kokoro Connect": "心連情結",
  "KonoSuba: God's Blessing on This Wonderful World!": "為美好的世界獻上祝福！",
  "Love Live! School Idol Project": "校園偶像計畫",
  "Lucky Star": "幸運星",
  "Magi: The Labyrinth of Magic": "魔奇少年",
  "Miss Kobayashi's Dragon Maid": "小林家的龍女僕",
  "Mobile Suit Gundam SEED": "機動戰士鋼彈 SEED",
  "Monthly Girls' Nozaki-kun": "月刊少女野崎同學",
  "My Hero Academia": "我的英雄學院",
  "My Love Story!!": "俺物語！！",
  "My Next Life as a Villainess: All Routes Lead to Doom!":
    "轉生成女性向遊戲只有毀滅結局的壞人大小姐",
  "My Teen Romantic Comedy SNAFU": "果然我的青春戀愛喜劇搞錯了",
  Nana: "娜娜",
  Naruto: "火影忍者",
  "Naruto Shippuden": "火影忍者疾風傳",
  "Naruto Shippūden": "火影忍者疾風傳",
  "Negima!?": "魔法老師",
  "Neon Genesis Evangelion": "新世紀福音戰士",
  Nisekoi: "偽戀",
  "Nisekoi: False Love": "偽戀",
  "No Game No Life": "遊戲人生",
  Noragami: "野良神",
  "Oh My Goddess!": "幸運女神",
  "One Piece": "航海王",
  "One Piece Film: Red": "航海王劇場版：紅髮歌姬",
  "One-Punch Man": "一拳超人",
  Oreimo: "我的妹妹哪有這麼可愛！",
  "Ouran High School Host Club": "櫻蘭高校男公關部",
  Pokémon: "寶可夢",
  "Princess Mononoke": "魔法公主",
  "Psycho-Pass": "心靈判官",
  "Puella Magi Madoka Magica": "魔法少女小圓",
  RWBY: "紅白黑黃",
  "Rascal Does Not Dream of Bunny Girl Senpai": "青春豬頭少年不會夢到兔女郎學姊",
  "Rent-A-Girlfriend": "租借女友",
  "Revolutionary Girl Utena": "少女革命",
  "Sailor Moon": "美少女戰士",
  Sankarea: "散華禮彌",
  Sekirei: "鶺鴒女神",
  "Seraph of the End": "終結的熾天使",
  "Shakugan no Shana": "灼眼的夏娜",
  "Soul Eater": "噬魂者",
  "Spirited Away": "神隱少女",
  "Spy x Family": "間諜家家酒",
  "Sword Art Online": "刀劍神域",
  "Tenjho Tenge": "天上天下",
  "That Time I Got Reincarnated as a Slime": "關於我轉生變成史萊姆這檔事",
  "The Ancient Magus' Bride": "魔法使的新娘",
  "The Irregular at Magic High School": "魔法科高中的劣等生",
  "The Melancholy of Haruhi Suzumiya": "涼宮春日的憂鬱",
  "The Pet Girl of Sakurasou": "櫻花莊的寵物女孩",
  "The Promised Neverland": "約定的夢幻島",
  "The Rising of The Shield Hero": "盾之勇者成名錄",
  "The Seven Deadly Sins": "七大罪",
  "To Love Ru": "出包王女",
  "Tokyo Ghoul": "東京喰種",
  "Toradora!": "龍與虎",
  "Trinity Seven": "七人魔法使",
  "Violet Evergarden": "紫羅蘭永恆花園",
  Watamote: "我不受歡迎，怎麼想都是你們的錯！",
  "Yona of the Dawn": "晨曦公主",
  "Your Name": "你的名字",
  "Yu-Gi-Oh!": "遊戲王",
  "Yu-Gi-Oh! GX": "遊戲王 GX",
  "Zero no Tsukaima": "零之使魔",
};

