import type { AtomInput } from "@/lib/validation/atoms";

import { EXPANDED_ANIME_CHARACTER_ATOMS } from "@/lib/seed/anime-character-atoms";
import { EXPANDED_MAIN_ATOMS } from "@/lib/seed/expanded-main-atoms";
import { EXPANDED_PERSONA_ADDON_ATOMS } from "@/lib/seed/expanded-persona-addons";

export type ExpandedAtomSource =
  | "anime-character-atoms"
  | "subject-hair-atoms"
  | "subject-atoms"
  | "body-atoms"
  | "styling-atoms-part-1"
  | "styling-atoms-part-2"
  | "scene-atoms"
  | "camera-atoms"
  | "media-atoms";

export type ExpandedAtom = AtomInput & {
  id: string;
  source: ExpandedAtomSource;
};

export const GENERATED_ATOM_PREVIEW_ROUTE_PREFIX = "/api/uploads/atom-previews/";

export const EXPANDED_HAIR_ATOMS = [
  {
    id: "seed-hair-airy-bangs",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "空氣瀏海",
    subtitle: "輕盈柔軟的瀏海與髮絲",
    previewImagePath: "/api/uploads/seed/soft-cinematic-young-woman-portrait-base.png",
    prompt: "airy bangs, soft layered hair, light wispy fringe, natural hair strands",
    negativePrompt: "helmet hair, stiff hair, unnatural hairline",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["瀏海", "髮型", "柔軟"],
    notes: "既有 seed。適合柔和日常人像，避免和厚重齊瀏海同時使用。",
  },
  {
    id: "library-hair-curtain-bangs",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "八字瀏海",
    subtitle: "自然分開並修飾臉側的瀏海",
    previewImagePath: "",
    prompt: "curtain bangs, parted face-framing fringe, soft layers around the cheeks",
    negativePrompt: "heavy blunt bangs, stiff fringe, uneven hairline",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["瀏海", "修飾臉型", "自然"],
    notes: "適合成熟自然的人像，比空氣瀏海更有臉側輪廓。",
  },
  {
    id: "library-hair-side-swept-bangs",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "側分瀏海",
    subtitle: "偏向一側的柔順瀏海線條",
    previewImagePath: "",
    prompt: "side-swept bangs, soft diagonal fringe, natural side part hair flow",
    negativePrompt: "flat forehead line, messy uneven bangs, helmet hair",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["瀏海", "側分", "柔順"],
    notes: "可用於輕成熟或編輯感人物，不改變整體髮長。",
  },
  {
    id: "library-hair-blunt-bangs",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "厚重齊瀏海",
    subtitle: "明確齊平的前額瀏海",
    previewImagePath: "",
    prompt: "blunt straight bangs, clean even fringe line, polished front hair shape",
    negativePrompt: "sparse bangs, uneven fringe, broken hairline",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["齊瀏海", "乾淨", "強輪廓"],
    notes: "控制力強，容易改變臉部印象，建議單獨使用。",
  },
  {
    id: "library-hair-no-bangs",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "露額中分",
    subtitle: "乾淨露出額頭的中分髮型",
    previewImagePath: "",
    prompt: "no bangs, clean center part, forehead visible, smooth face-framing hair",
    negativePrompt: "random fringe, messy bangs, hidden forehead",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["露額", "中分", "乾淨"],
    notes: "適合清冷或成熟感人設，可避免模型自動加瀏海。",
  },
  {
    id: "library-hair-high-ponytail",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "高馬尾",
    subtitle: "俐落向上束起的馬尾",
    previewImagePath: "",
    prompt: "high ponytail, lifted tied hair, clean sporty silhouette, loose natural strands",
    negativePrompt: "low ponytail, messy hair knot, duplicated ponytail",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["馬尾", "俐落", "活力"],
    notes: "適合元氣、運動感或街拍姿態。",
  },
  {
    id: "library-hair-low-ponytail",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "低馬尾",
    subtitle: "靠近頸後的柔和束髮",
    previewImagePath: "",
    prompt: "low ponytail, relaxed tied hair at the nape, soft loose strands",
    negativePrompt: "high ponytail, stiff tied hair, tangled ponytail",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["馬尾", "低束髮", "溫柔"],
    notes: "適合室內、通勤、安靜氛圍。",
  },
  {
    id: "library-hair-loose-side-ponytail",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "側邊低馬尾",
    subtitle: "偏向一側垂落的低馬尾",
    previewImagePath: "",
    prompt: "loose side ponytail, hair gathered over one shoulder, relaxed asymmetrical silhouette",
    negativePrompt: "centered ponytail, stiff hair, duplicated hair mass",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["馬尾", "側邊", "慵懶"],
    notes: "能增加輕微動態與不對稱感。",
  },
  {
    id: "library-hair-twin-tails",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "雙馬尾",
    subtitle: "兩側對稱束起的年輕感髮型",
    previewImagePath: "",
    prompt: "twin tails, symmetrical tied hair on both sides, playful youthful hairstyle",
    negativePrompt: "single ponytail, uneven twin tails, childish exaggeration",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["雙馬尾", "可愛", "對稱"],
    notes: "適合活潑社群感，避免和成熟人設衝突。",
  },
  {
    id: "library-hair-low-twin-tails",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "低雙馬尾",
    subtitle: "位置較低的柔和雙束髮",
    previewImagePath: "",
    prompt: "low twin tails, softly tied hair near the shoulders, gentle symmetrical hairstyle",
    negativePrompt: "high pigtails, messy knots, uneven hair length",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["雙馬尾", "低束髮", "柔和"],
    notes: "比普通雙馬尾更安靜，適合日常或復古感。",
  },
  {
    id: "library-hair-half-up",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "半扎髮",
    subtitle: "上半部束起、下半部自然垂落",
    previewImagePath: "",
    prompt: "half-up hairstyle, upper hair gently tied back, lower hair falling naturally",
    negativePrompt: "full ponytail, messy hair clip, stiff half-up shape",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["半扎", "溫柔", "層次"],
    notes: "可搭配臉部特徵與妝容，不搶服裝主體。",
  },
  {
    id: "library-hair-messy-bun",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "慵懶丸子頭",
    subtitle: "鬆散自然的高位丸子頭",
    previewImagePath: "",
    prompt: "messy bun, relaxed top knot, soft loose flyaway strands, casual tied hair",
    negativePrompt: "perfect hard bun, tangled hair, broken hair anatomy",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["丸子頭", "慵懶", "隨性"],
    notes: "適合居家、咖啡店、隨手拍氛圍。",
  },
  {
    id: "library-hair-low-bun",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "低盤髮",
    subtitle: "頸後收束的乾淨低盤髮",
    previewImagePath: "",
    prompt: "low bun, neat hair gathered at the nape, elegant soft updo",
    negativePrompt: "high bun, messy knot, loose collapsed bun",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["盤髮", "優雅", "低束"],
    notes: "適合編輯感、正式造型或溫柔室內光。",
  },
  {
    id: "library-hair-space-buns",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "雙丸子頭",
    subtitle: "兩側對稱的小丸子輪廓",
    previewImagePath: "",
    prompt: "space buns, two small buns on both sides, playful symmetrical updo",
    negativePrompt: "one bun only, uneven buns, excessive cartoon styling",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["丸子頭", "雙髻", "玩味"],
    notes: "適合 Y2K、貼紙版式或年輕街拍。",
  },
  {
    id: "library-hair-long-straight-black",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "黑長直",
    subtitle: "乾淨垂順的深色長直髮",
    previewImagePath: "",
    prompt: "long straight black hair, smooth glossy strands, clean vertical hair silhouette",
    negativePrompt: "frizzy hair, uneven extensions, unnatural black shine",
    priority: "strong",
    lockPolicy: "normal",
    tags: ["長髮", "黑髮", "直髮"],
    notes: "控制力強，會明顯改變角色印象。",
  },
  {
    id: "library-hair-long-loose-waves",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "長髮大波浪",
    subtitle: "柔軟自然的大弧度捲髮",
    previewImagePath: "",
    prompt: "long loose waves, soft flowing curls, natural volume, relaxed hair movement",
    negativePrompt: "tight ringlets, messy tangles, stiff curls",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["長髮", "波浪", "柔軟"],
    notes: "適合旅行、街拍、溫柔人像。",
  },
  {
    id: "library-hair-beach-waves",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "海風波浪髮",
    subtitle: "帶有自然凌亂感的波浪髮",
    previewImagePath: "",
    prompt: "beach waves, tousled wavy hair, natural windswept texture, effortless volume",
    negativePrompt: "wet tangled hair, over-styled curls, stiff waves",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["波浪", "隨性", "旅行"],
    notes: "適合戶外、夏日、海邊或旅行素材。",
  },
  {
    id: "library-hair-soft-curls",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "髮尾微卷",
    subtitle: "髮尾帶有低調捲度",
    previewImagePath: "",
    prompt: "softly curled hair ends, subtle inward curls, gentle polished hair tips",
    negativePrompt: "tight curls, uneven curled ends, burned hair texture",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["微卷", "髮尾", "低調"],
    notes: "是安全泛用的變體，不會過度改變人物。",
  },
  {
    id: "library-hair-straight-lob",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "及肩直髮",
    subtitle: "落在肩線附近的直髮長度",
    previewImagePath: "",
    prompt: "straight lob haircut, shoulder-length smooth hair, clean minimal silhouette",
    negativePrompt: "very long hair, pixie cut, uneven haircut",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["及肩", "直髮", "清爽"],
    notes: "適合通勤、清冷、簡潔人像。",
  },
  {
    id: "library-hair-wavy-lob",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "及肩微捲",
    subtitle: "及肩長度加上自然捲度",
    previewImagePath: "",
    prompt: "wavy lob haircut, shoulder-length soft waves, natural airy volume",
    negativePrompt: "long curls, flat straight hair, messy frizz",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["及肩", "微捲", "自然"],
    notes: "比直髮更有生活感與柔和度。",
  },
  {
    id: "library-hair-short-bob",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "短髮波波頭",
    subtitle: "乾淨圓潤的短髮輪廓",
    previewImagePath: "",
    prompt: "short bob haircut, rounded clean hair shape, chin-length polished silhouette",
    negativePrompt: "long hair, uneven bob, helmet-like hair",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["短髮", "波波頭", "乾淨"],
    notes: "適合甜美、復古或清爽人設。",
  },
  {
    id: "library-hair-blunt-bob",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "一刀切短髮",
    subtitle: "髮尾齊平的銳利短髮",
    previewImagePath: "",
    prompt: "blunt bob haircut, sharp even hair ends, sleek geometric silhouette",
    negativePrompt: "feathered layers, messy ends, uneven cut",
    priority: "strong",
    lockPolicy: "normal",
    tags: ["短髮", "一刀切", "銳利"],
    notes: "輪廓感強，適合清冷或時尚編輯風。",
  },
  {
    id: "library-hair-pixie-cut",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "精靈短髮",
    subtitle: "露出耳側與頸線的俐落短髮",
    previewImagePath: "",
    prompt: "pixie cut, very short layered hair, clean ears and neck silhouette",
    negativePrompt: "long hair, bulky sides, uneven cropped hair",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["短髮", "俐落", "中性"],
    notes: "適合乾淨、有個性的角色基底。",
  },
  {
    id: "library-hair-wolf-cut",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "狼尾層次髮",
    subtitle: "上短下長的強層次髮型",
    previewImagePath: "",
    prompt: "wolf cut hairstyle, shaggy layered hair, longer nape layers, edgy silhouette",
    negativePrompt: "flat one-length hair, messy broken layers, mullet exaggeration",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["狼尾", "層次", "甜酷"],
    notes: "適合街拍、甜酷、地下偶像感。",
  },
  {
    id: "library-hair-hush-cut",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "韓系層次髮",
    subtitle: "柔順自然的空氣感層次",
    previewImagePath: "",
    prompt: "hush cut hairstyle, soft Korean-inspired layers, airy face-framing movement",
    negativePrompt: "harsh choppy layers, stiff hair, heavy blunt cut",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["層次", "韓系", "柔順"],
    notes: "泛用度高，可搭配多數人設與場景。",
  },
  {
    id: "library-hair-hime-cut",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "姬髮式",
    subtitle: "臉側齊切與長髮形成對比",
    previewImagePath: "",
    prompt: "hime cut, straight side locks cut at cheek length, long smooth back hair",
    negativePrompt: "uneven side locks, messy layered hair, random bangs",
    priority: "strong",
    lockPolicy: "normal",
    tags: ["姬髮式", "長髮", "輪廓"],
    notes: "非常有辨識度，適合需要強角色記憶點時使用。",
  },
  {
    id: "library-hair-princess-cut",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "公主切長髮",
    subtitle: "整齊臉側髮束與柔順長髮",
    previewImagePath: "",
    prompt: "princess cut long hair, neat face-side sections, polished long hair silhouette",
    negativePrompt: "messy side hair, broken hairline, uneven cut",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["公主切", "長髮", "整齊"],
    notes: "比姬髮式更柔和，適合甜美或清冷人像。",
  },
  {
    id: "library-hair-single-side-braid",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "側邊麻花辮",
    subtitle: "垂在一側肩前的編髮",
    previewImagePath: "",
    prompt: "single side braid, loose braid resting over one shoulder, soft woven hair texture",
    negativePrompt: "two braids, tangled braid, stiff rope-like hair",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["編髮", "側邊", "溫柔"],
    notes: "適合田園、旅行、窗邊或咖啡店場景。",
  },
  {
    id: "library-hair-double-braids",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "雙麻花辮",
    subtitle: "兩側垂落的對稱編髮",
    previewImagePath: "",
    prompt: "double braids, two neat braided pigtails, symmetrical woven hair",
    negativePrompt: "single braid, uneven braids, childish exaggeration",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["編髮", "對稱", "復古"],
    notes: "適合復古、學院、清新日常風。",
  },
  {
    id: "library-hair-crown-braid",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "低調編髮髮冠",
    subtitle: "頭側環繞的細緻編髮",
    previewImagePath: "",
    prompt: "subtle crown braid, braided hair detail around the head, delicate romantic texture",
    negativePrompt: "oversized braid crown, messy tangled braid, costume wig",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["編髮", "髮冠", "浪漫"],
    notes: "適合花園、婚禮感、柔和光影，但不要和過多配飾疊太滿。",
  },
  {
    id: "library-hair-wet-hair",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "濕髮感",
    subtitle: "帶有水氣與貼合感的髮絲",
    previewImagePath: "",
    prompt: "wet hair look, damp glossy strands, slightly clinging hair texture",
    negativePrompt: "greasy hair, dirty hair, plastic shine",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["濕髮", "光澤", "張力"],
    notes: "適合雨夜、浴室鏡前或高張力寫真。",
  },
  {
    id: "library-hair-bedhead",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "剛睡醒亂髮",
    subtitle: "自然凌亂但合理的睡醒髮流",
    previewImagePath: "",
    prompt: "bedhead hair, natural messy strands, soft unstyled morning texture",
    negativePrompt: "dirty hair, severe tangles, broken hair shape",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["亂髮", "居家", "自然"],
    notes: "適合生活流瞬間與非棚拍感。",
  },
  {
    id: "library-hair-windswept",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "被風吹亂的髮絲",
    subtitle: "風造成的自然髮流與飛絲",
    previewImagePath: "",
    prompt: "windswept hair, natural flyaway strands, hair moving with gentle wind",
    negativePrompt: "extreme storm hair, tangled mess, frozen hair strands",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["風感", "飛絲", "動態"],
    notes: "適合戶外、街拍、旅行，不應同時搭配過於整齊的髮型。",
  },
  {
    id: "library-hair-face-framing-strands",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "臉側碎髮",
    subtitle: "臉頰附近自然垂落的小髮束",
    previewImagePath: "",
    prompt: "loose face-framing strands, soft hair pieces near the cheeks, natural flyaways",
    negativePrompt: "stiff side locks, messy tangled strands, blocked face",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["碎髮", "臉側", "自然"],
    notes: "可強化真實感，和多數髮型相容。",
  },
  {
    id: "library-hair-pastel-pink-brown",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "粉棕髮色",
    subtitle: "柔和不誇張的粉棕色調",
    previewImagePath: "",
    prompt: "soft pink-brown hair color, muted rosy brown tone, natural dyed hair finish",
    negativePrompt: "neon pink hair, patchy dye, oversaturated color",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["染髮", "粉棕", "柔和"],
    notes: "適合日系、社群感、溫柔人像。",
  },
  {
    id: "library-hair-ash-brown",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "亞麻灰棕髮",
    subtitle: "低飽和冷調棕色髮色",
    previewImagePath: "",
    prompt: "ash brown hair color, muted cool brown tone, soft low-saturation dye",
    negativePrompt: "orange hair, oversaturated brown, uneven dye patches",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["染髮", "灰棕", "低飽和"],
    notes: "適合清冷、膠片與城市街拍。",
  },
  {
    id: "library-hair-silver-gray",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "銀灰髮色",
    subtitle: "帶未來感的冷銀灰髮",
    previewImagePath: "",
    prompt: "silver gray hair color, cool metallic ash tone, smooth dyed hair texture",
    negativePrompt: "white wig, patchy gray dye, plastic shine",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["染髮", "銀灰", "未來感"],
    notes: "風格感強，適合未來感、街頭或編輯寫真。",
  },
  {
    id: "library-hair-highlight-streaks",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "挑染髮束",
    subtitle: "局部可見的對比色挑染",
    previewImagePath: "",
    prompt: "subtle highlight streaks, selective dyed hair strands, visible color accents",
    negativePrompt: "full rainbow hair, messy dye patches, harsh stripes",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["挑染", "髮色", "亮點"],
    notes: "用來增加小範圍角色記憶點，不取代整體髮型。",
  },
  {
    id: "library-hair-ombre-gradient",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "漸層髮色",
    subtitle: "從髮根到髮尾自然過渡的染髮",
    previewImagePath: "",
    prompt: "ombre gradient hair color, natural transition from darker roots to lighter ends",
    negativePrompt: "harsh color block, patchy gradient, unnatural dye line",
    priority: "medium",
    lockPolicy: "normal",
    tags: ["漸層", "染髮", "髮尾"],
    notes: "適合 Y2K、社群封面或時尚感人像。",
  },
  {
    id: "library-hair-slicked-back",
    source: "subject-hair-atoms",
    category: "髮型",
    title: "後梳濕亮髮",
    subtitle: "額頭露出、髮絲向後貼順",
    previewImagePath: "",
    prompt: "slicked-back hair, forehead exposed, glossy controlled hair swept backward",
    negativePrompt: "messy bangs, dry frizzy hair, random loose fringe",
    priority: "strong",
    lockPolicy: "normal",
    tags: ["後梳", "露額", "張力"],
    notes: "控制力強，適合成熟、冷感或高對比光影。",
  },
] satisfies ExpandedAtom[];

export const EXPANDED_ATOMS = [
  ...EXPANDED_HAIR_ATOMS,
  ...EXPANDED_MAIN_ATOMS,
  ...EXPANDED_PERSONA_ADDON_ATOMS,
  ...EXPANDED_ANIME_CHARACTER_ATOMS,
] satisfies ExpandedAtom[];

export { EXPANDED_ANIME_CHARACTER_ATOMS } from "@/lib/seed/anime-character-atoms";
export { EXPANDED_PERSONA_ADDON_ATOMS } from "@/lib/seed/expanded-persona-addons";
