import type { AtomInput } from "@/lib/validation/atoms";

export const SEED_ATOMS: Array<AtomInput & { id: string }> = [
  {
    id: "seed-persona-soft-cinematic",
    category: "人設",
    title: "柔和電影感少女",
    subtitle: "乾淨自然的人像基底",
    previewImagePath: "/api/uploads/seed/soft-cinematic-young-woman-portrait-base.png",
    prompt: "soft cinematic young woman portrait base, natural features, gentle presence, clean editorial portrait",
    negativePrompt: "celebrity likeness, brand logo, watermark",
    tags: ["人像", "電影感", "自然"],
    notes: "適合作為日常寫真人設基底，後續可疊加服裝、場景與光影。",
  },
  {
    id: "seed-expression-playful-smile",
    category: "表情",
    title: "俏皮自信微笑",
    subtitle: "甜美看鏡頭的表情",
    previewImagePath: "/api/uploads/seed/playful-confident-smile.png",
    prompt: "playful confident smile, soft sweet expression, looking directly at camera",
    negativePrompt: "exaggerated grin, distorted face",
    tags: ["微笑", "俏皮", "看鏡頭"],
    notes: "適合自拍、半身照與社群感寫真。",
  },
  {
    id: "seed-pose-mirror-selfie",
    category: "姿態",
    title: "鏡前自拍姿態",
    subtitle: "自然站姿與手機自拍",
    previewImagePath: "/api/uploads/seed/mirror-selfie-pose.png",
    prompt: "casual mirror selfie pose, relaxed posture, one hand holding phone, natural body angle",
    negativePrompt: "awkward anatomy, extra fingers",
    tags: ["自拍", "站姿", "手機"],
    notes: "可搭配臥室、穿搭與 SNS 快照風格。",
  },
  {
    id: "seed-top-cropped-knit-cardigan",
    category: "上裝",
    title: "短版針織開衫",
    subtitle: "柔軟休閒的上身穿搭",
    previewImagePath: "/api/uploads/seed/cropped-knit-cardigan.png",
    prompt: "cropped knit cardigan, soft textured fabric, casual fitted silhouette",
    negativePrompt: "brand logo, text print",
    tags: ["針織", "短版", "休閒"],
    notes: "適合甜美、日常與室內寫真組合。",
  },
  {
    id: "seed-bottom-pleated-mini-skirt",
    category: "下裝",
    title: "百褶短裙",
    subtitle: "輕盈學院感下裝",
    previewImagePath: "/api/uploads/seed/pleated-mini-skirt.png",
    prompt: "pleated mini skirt, clean school-inspired styling, neat fabric folds",
    negativePrompt: "brand logo, messy folds",
    tags: ["百褶", "學院感", "短裙"],
    notes: "可和短版開衫、平台鞋與半身景別搭配。",
  },
  {
    id: "seed-shoes-platform-sneakers",
    category: "鞋履",
    title: "厚底休閒球鞋",
    subtitle: "街頭感平台鞋輪廓",
    previewImagePath: "/api/uploads/seed/chunky-platform-sneakers.png",
    prompt: "chunky platform sneakers, clean white streetwear shoes, thick sole silhouette",
    negativePrompt: "brand logo, dirty shoes",
    tags: ["厚底", "球鞋", "街頭"],
    notes: "用於增加休閒、年輕與街拍感。",
  },
  {
    id: "seed-scene-cozy-bedroom",
    category: "場景",
    title: "溫馨臥室角落",
    subtitle: "柔軟布料與自然生活感",
    previewImagePath: "/api/uploads/seed/cozy-bedroom-corner.png",
    prompt: "cozy bedroom corner, soft bedding, warm personal interior, tidy lived-in details",
    negativePrompt: "messy room, visible brand posters",
    tags: ["臥室", "溫馨", "生活感"],
    notes: "適合自拍、穿搭展示與柔和窗光。",
  },
  {
    id: "seed-style-sns-snapshot",
    category: "寫真風格",
    title: "社群手機快照",
    subtitle: "自然、不過度修飾的 SNS 感",
    previewImagePath: "/api/uploads/seed/sns-smartphone-snapshot.png",
    prompt: "SNS smartphone snapshot style, casual social media photo, natural imperfections, spontaneous framing",
    negativePrompt: "overly polished studio look",
    tags: ["社群", "手機", "自然"],
    notes: "讓成片更像日常手機拍攝，而非商業棚拍。",
  },
  {
    id: "seed-light-warm-window",
    category: "光影",
    title: "暖色窗邊光",
    subtitle: "午後自然光落在人物上",
    previewImagePath: "/api/uploads/seed/warm-window-light.png",
    prompt: "warm window light, soft afternoon sunlight, gentle highlights and natural shadows",
    negativePrompt: "harsh overexposure, neon lighting",
    tags: ["暖光", "窗光", "午後"],
    notes: "適合增加溫柔、私密與生活感氛圍。",
  },
  {
    id: "seed-effect-subtle-film-grain",
    category: "畫面影響",
    title: "細緻底片顆粒",
    subtitle: "低調膠片質感覆蓋",
    previewImagePath: "/api/uploads/seed/subtle-film-grain-overlay.png",
    prompt: "subtle film grain overlay, fine analog texture, gentle imperfections",
    negativePrompt: "heavy noise, dirty scratches",
    tags: ["顆粒", "底片", "質感"],
    notes: "多選素材，可疊加在不同完整 Prompt 上增加自然感。",
  },
  {
    id: "seed-layout-scrapbook-stickers",
    category: "版式設計",
    title: "手帳貼紙版式",
    subtitle: "輕微拼貼與裝飾邊角",
    previewImagePath: "/api/uploads/seed/scrapbook-sticker-layout.png",
    prompt: "scrapbook sticker layout, subtle collage accents, decorative corner stickers, playful framing",
    negativePrompt: "busy clutter, unreadable text",
    tags: ["手帳", "貼紙", "拼貼"],
    notes: "多選素材，適合做社群封面或可愛版式變體。",
  },
  {
    id: "seed-accessory-silver-hoops",
    category: "配飾",
    title: "銀色圈形耳環",
    subtitle: "乾淨亮面金屬小配件",
    previewImagePath: "/api/uploads/seed/silver-hoop-earrings.png",
    prompt: "silver hoop earrings, clean reflective metal accessory, subtle fashion detail",
    negativePrompt: "oversized jewelry, brand logo",
    tags: ["耳環", "銀色", "金屬"],
    notes: "多選素材，可與妝容和半身景別搭配突出細節。",
  },
  {
    id: "seed-prop-phone-in-hand",
    category: "道具",
    title: "手持手機",
    subtitle: "自拍或日常紀錄道具",
    previewImagePath: "/api/uploads/seed/phone-in-hand.png",
    prompt: "phone in hand, casual everyday prop, natural grip, modern smartphone without visible brand",
    negativePrompt: "brand logo, broken screen",
    tags: ["手機", "自拍", "道具"],
    notes: "多選素材，常用於鏡前自拍與 SNS 快照。",
  },
  {
    id: "seed-lens-phone-flash",
    category: "鏡頭質感",
    title: "業餘手機閃光",
    subtitle: "近距離直接閃燈質感",
    previewImagePath: "/api/uploads/seed/amateur-phone-flash.png",
    prompt: "amateur phone flash, direct on-camera flash, candid compact-camera feeling",
    negativePrompt: "professional studio lighting",
    tags: ["閃光", "手機感", "快照"],
    notes: "讓畫面更像私人記錄與夜間快照。",
  },
  {
    id: "seed-framing-half-body",
    category: "景別",
    title: "半身景別",
    subtitle: "保留穿搭與表情重點",
    previewImagePath: "/api/uploads/seed/half-body-framing.png",
    prompt: "half-body framing, waist-up portrait composition, balanced face and outfit visibility",
    negativePrompt: "extreme close-up, cropped head",
    tags: ["半身", "構圖", "穿搭"],
    notes: "適合展示上裝、配飾與表情。",
  },
  {
    id: "seed-makeup-soft-idol",
    category: "妝容",
    title: "柔和偶像妝",
    subtitle: "清透眼妝與自然唇色",
    previewImagePath: "/api/uploads/seed/soft-idol-makeup.png",
    prompt: "soft idol makeup, clean glowing skin, subtle eye makeup, natural glossy lips",
    negativePrompt: "heavy dramatic makeup, smeared cosmetics",
    tags: ["清透", "偶像感", "自然"],
    notes: "適合甜美人像、自拍與暖光場景。",
  },
];
