import type { AtomInput } from "@/lib/validation/atoms";

export const SEED_ATOMS: Array<
  Omit<AtomInput, "priority" | "lockPolicy"> &
    Partial<Pick<AtomInput, "priority" | "lockPolicy">> & { id: string }
> = [
  {
    id: "seed-persona-soft-cinematic",
    category: "人設",
    title: "柔和電影感少女",
    subtitle: "乾淨自然的人像基底",
    previewImagePath: "/api/uploads/seed/soft-cinematic-young-woman-portrait-base.png",
    prompt: "soft cinematic young woman portrait base, natural features, gentle presence, clean editorial portrait",
    negativePrompt: "celebrity likeness, brand logo, watermark",
    tags: ["人像", "電影感", "自然"],
    notes: "適合作為日常寫真人設基底，後續可疊加服裝、場景與光影。",
  },
  {
    id: "seed-expression-playful-smile",
    category: "表情",
    title: "俏皮自信微笑",
    subtitle: "甜美看鏡頭的表情",
    previewImagePath: "/api/uploads/seed/playful-confident-smile.png",
    prompt: "playful confident smile, soft sweet expression, looking directly at camera",
    negativePrompt: "exaggerated grin, distorted face",
    tags: ["微笑", "俏皮", "看鏡頭"],
    notes: "適合自拍、半身照與社群感寫真。",
  },
  {
    id: "seed-pose-mirror-selfie",
    category: "姿態",
    title: "鏡前自拍姿態",
    subtitle: "自然站姿與手機自拍",
    previewImagePath: "/api/uploads/seed/mirror-selfie-pose.png",
    prompt: "casual mirror selfie pose, relaxed posture, one hand holding phone, natural body angle",
    negativePrompt: "awkward anatomy, extra fingers",
    tags: ["自拍", "站姿", "手機"],
    notes: "可搭配臥室、穿搭與 SNS 快照風格。",
  },
  {
    id: "seed-top-cropped-knit-cardigan",
    category: "上裝",
    title: "短版針織開衫",
    subtitle: "柔軟休閒的上身穿搭",
    previewImagePath: "/api/uploads/seed/cropped-knit-cardigan.png",
    prompt: "cropped knit cardigan, soft textured fabric, casual fitted silhouette",
    negativePrompt: "brand logo, text print",
    tags: ["針織", "短版", "休閒"],
    notes: "適合甜美、日常與室內寫真組合。",
  },
  {
    id: "seed-bottom-pleated-mini-skirt",
    category: "下裝",
    title: "百褶短裙",
    subtitle: "輕盈學院感下裝",
    previewImagePath: "/api/uploads/seed/pleated-mini-skirt.png",
    prompt: "pleated mini skirt, clean school-inspired styling, neat fabric folds",
    negativePrompt: "brand logo, messy folds",
    tags: ["百褶", "學院感", "短裙"],
    notes: "可和短版開衫、平台鞋與半身景別搭配。",
  },
  {
    id: "seed-shoes-platform-sneakers",
    category: "鞋履",
    title: "厚底休閒球鞋",
    subtitle: "街頭感平台鞋輪廓",
    previewImagePath: "/api/uploads/seed/chunky-platform-sneakers.png",
    prompt: "chunky platform sneakers, clean white streetwear shoes, thick sole silhouette",
    negativePrompt: "brand logo, dirty shoes",
    tags: ["厚底", "球鞋", "街頭"],
    notes: "用於增加休閒、年輕與街拍感。",
  },
  {
    id: "seed-scene-cozy-bedroom",
    category: "場景",
    title: "溫馨臥室角落",
    subtitle: "柔軟布料與自然生活感",
    previewImagePath: "/api/uploads/seed/cozy-bedroom-corner.png",
    prompt: "cozy bedroom corner, soft bedding, warm personal interior, tidy lived-in details",
    negativePrompt: "messy room, visible brand posters",
    tags: ["臥室", "溫馨", "生活感"],
    notes: "適合自拍、穿搭展示與柔和窗光。",
  },
  {
    id: "seed-style-sns-snapshot",
    category: "寫真風格",
    title: "社群手機快照",
    subtitle: "自然、不過度修飾的 SNS 感",
    previewImagePath: "/api/uploads/seed/sns-smartphone-snapshot.png",
    prompt: "SNS smartphone snapshot style, casual social media photo, natural imperfections, spontaneous framing",
    negativePrompt: "overly polished studio look",
    tags: ["社群", "手機", "自然"],
    notes: "讓成片更像日常手機拍攝，而非商業棚拍。",
  },
  {
    id: "seed-light-warm-window",
    category: "光影",
    title: "暖色窗邊光",
    subtitle: "午後自然光落在人物上",
    previewImagePath: "/api/uploads/seed/warm-window-light.png",
    prompt: "warm window light, soft afternoon sunlight, gentle highlights and natural shadows",
    negativePrompt: "harsh overexposure, neon lighting",
    tags: ["暖光", "窗光", "午後"],
    notes: "適合增加溫柔、私密與生活感氛圍。",
  },
  {
    id: "seed-effect-subtle-film-grain",
    category: "畫面影響",
    title: "細緻底片顆粒",
    subtitle: "低調膠片質感覆蓋",
    previewImagePath: "/api/uploads/seed/subtle-film-grain-overlay.png",
    prompt: "subtle film grain overlay, fine analog texture, gentle imperfections",
    negativePrompt: "heavy noise, dirty scratches",
    tags: ["顆粒", "底片", "質感"],
    notes: "多選素材，可疊加在不同完整 Prompt 上增加自然感。",
  },
  {
    id: "seed-layout-scrapbook-stickers",
    category: "版式設計",
    title: "手帳貼紙版式",
    subtitle: "輕微拼貼與裝飾邊角",
    previewImagePath: "/api/uploads/seed/scrapbook-sticker-layout.png",
    prompt: "scrapbook sticker layout, subtle collage accents, decorative corner stickers, playful framing",
    negativePrompt: "busy clutter, unreadable text",
    tags: ["手帳", "貼紙", "拼貼"],
    notes: "多選素材，適合做社群封面或可愛版式變體。",
  },
  {
    id: "seed-accessory-silver-hoops",
    category: "配飾",
    title: "銀色圈形耳環",
    subtitle: "乾淨亮面金屬小配件",
    previewImagePath: "/api/uploads/seed/silver-hoop-earrings.png",
    prompt: "silver hoop earrings, clean reflective metal accessory, subtle fashion detail",
    negativePrompt: "oversized jewelry, brand logo",
    tags: ["耳環", "銀色", "金屬"],
    notes: "多選素材，可與妝容和半身景別搭配突出細節。",
  },
  {
    id: "seed-prop-phone-in-hand",
    category: "道具",
    title: "手持手機",
    subtitle: "自拍或日常紀錄道具",
    previewImagePath: "/api/uploads/seed/phone-in-hand.png",
    prompt: "phone in hand, casual everyday prop, natural grip, modern smartphone without visible brand",
    negativePrompt: "brand logo, broken screen",
    tags: ["手機", "自拍", "道具"],
    notes: "多選素材，常用於鏡前自拍與 SNS 快照。",
  },
  {
    id: "seed-lens-phone-flash",
    category: "鏡頭質感",
    title: "業餘手機閃光",
    subtitle: "近距離直接閃燈質感",
    previewImagePath: "/api/uploads/seed/amateur-phone-flash.png",
    prompt: "amateur phone flash, direct on-camera flash, candid compact-camera feeling",
    negativePrompt: "professional studio lighting",
    tags: ["閃光", "手機感", "快照"],
    notes: "讓畫面更像私人記錄與夜間快照。",
  },
  {
    id: "seed-framing-half-body",
    category: "景別",
    title: "半身景別",
    subtitle: "保留穿搭與表情重點",
    previewImagePath: "/api/uploads/seed/half-body-framing.png",
    prompt: "half-body framing, waist-up portrait composition, balanced face and outfit visibility",
    negativePrompt: "extreme close-up, cropped head",
    tags: ["半身", "構圖", "穿搭"],
    notes: "適合展示上裝、配飾與表情。",
  },
  {
    id: "seed-makeup-soft-idol",
    category: "妝容",
    title: "柔和偶像妝",
    subtitle: "清透眼妝與自然唇色",
    previewImagePath: "/api/uploads/seed/soft-idol-makeup.png",
    prompt: "soft idol makeup, clean glowing skin, subtle eye makeup, natural glossy lips",
    negativePrompt: "heavy dramatic makeup, smeared cosmetics",
    tags: ["清透", "偶像感", "自然"],
    notes: "適合甜美人像、自拍與暖光場景。",
  },
  {
    id: "seed-subject-solo",
    category: "主體數量 / 人物關係",
    title: "單人主體",
    subtitle: "明確只有一位主要人物",
    previewImagePath: "/api/uploads/seed/soft-cinematic-young-woman-portrait-base.png",
    prompt: "solo subject, one main person only, clear single-person portrait focus",
    negativePrompt: "extra people, crowd, duplicated subject",
    priority: "strong",
    tags: ["單人", "主體", "人像"],
    notes: "用於固定畫面只有一位主體，避免生成額外人物。",
  },
  {
    id: "seed-face-droopy-eyes",
    category: "臉部特徵",
    title: "下垂眼柔和臉",
    subtitle: "溫柔無攻擊性的五官印象",
    previewImagePath: "/api/uploads/seed/soft-cinematic-young-woman-portrait-base.png",
    prompt: "soft facial features, gentle droopy eyes, delicate face shape, natural skin texture",
    negativePrompt: "harsh facial expression, exaggerated facial structure",
    tags: ["五官", "下垂眼", "柔和"],
    notes: "從人設中拆出的臉部細節，可與不同髮型和表情組合。",
  },
  {
    id: "seed-hair-airy-bangs",
    category: "髮型",
    title: "空氣瀏海",
    subtitle: "輕盈柔軟的瀏海與髮絲",
    previewImagePath: "/api/uploads/seed/soft-cinematic-young-woman-portrait-base.png",
    prompt: "airy bangs, soft layered hair, light wispy fringe, natural hair strands",
    negativePrompt: "helmet hair, stiff hair, unnatural hairline",
    tags: ["瀏海", "髮型", "柔軟"],
    notes: "讓髮型獨立控制，不混在人設描述裡。",
  },
  {
    id: "seed-eye-direct-camera",
    category: "視線",
    title: "直視鏡頭",
    subtitle: "建立清楚的眼神連結",
    previewImagePath: "/api/uploads/seed/playful-confident-smile.png",
    prompt: "direct eye contact with camera, focused gaze, clear viewer connection",
    negativePrompt: "cross-eyed gaze, unfocused eyes, looking in random directions",
    tags: ["視線", "看鏡頭", "眼神"],
    notes: "適合自拍、人像封面與需要互動感的構圖。",
  },
  {
    id: "seed-hand-cheek",
    category: "手部動作",
    title: "手托腮",
    subtitle: "柔和親近的局部手勢",
    previewImagePath: "/api/uploads/seed/phone-in-hand.png",
    prompt: "one hand gently resting on cheek, relaxed fingers, natural hand gesture",
    negativePrompt: "extra fingers, malformed hands, fused fingers",
    priority: "strong",
    tags: ["手勢", "托腮", "親近"],
    notes: "可疊加在坐姿、自拍或窗邊人像中。",
  },
  {
    id: "seed-body-bust-framing",
    category: "身體構圖",
    title: "半身身體構圖",
    subtitle: "保留頭肩與上半身比例",
    previewImagePath: "/api/uploads/seed/half-body-framing.png",
    prompt: "bust body framing, head and upper torso visible, clean shoulder line",
    negativePrompt: "missing shoulders, awkward crop, cut-off face",
    tags: ["半身", "身體", "比例"],
    notes: "用於控制身體露出比例，和景別的鏡頭距離分開管理。",
  },
  {
    id: "seed-scene-detail-bedside-lamp",
    category: "場景細節",
    title: "床邊小夜燈",
    subtitle: "臥室背景中的生活細節",
    previewImagePath: "/api/uploads/seed/cozy-bedroom-corner.png",
    prompt: "small bedside lamp in the background, cozy personal room detail, soft warm accent",
    negativePrompt: "messy cables, brand logo, distracting background text",
    tags: ["背景", "小夜燈", "生活感"],
    notes: "讓場景細節可疊加，不取代主要場景。",
  },
  {
    id: "seed-interaction-mirror-selfie",
    category: "互動行為",
    title: "鏡前自拍",
    subtitle: "人物與手機及鏡面的互動",
    previewImagePath: "/api/uploads/seed/mirror-selfie-pose.png",
    prompt: "taking a mirror selfie, interacting with phone and mirror reflection, casual personal moment",
    negativePrompt: "impossible reflection, duplicated phone, distorted mirror",
    tags: ["互動", "自拍", "鏡子"],
    notes: "作為行為 atom，可與姿態、道具和鏡頭角度分開控制。",
  },
  {
    id: "seed-time-rainy-night",
    category: "時間 / 季節 / 天氣",
    title: "雨夜",
    subtitle: "夜晚雨後的濕潤氛圍",
    previewImagePath: "/api/uploads/seed/amateur-phone-flash.png",
    prompt: "rainy night atmosphere, wet pavement reflections, humid evening air",
    negativePrompt: "bright sunny day, dry pavement",
    tags: ["雨夜", "天氣", "夜晚"],
    notes: "用於指定時間與天氣，不與場景或光影混在一起。",
  },
  {
    id: "seed-color-cool-blue-night",
    category: "色彩系統",
    title: "冷藍夜色",
    subtitle: "偏冷的藍色主調",
    previewImagePath: "/api/uploads/seed/amateur-phone-flash.png",
    prompt: "cool blue night color palette, muted cyan shadows, restrained low-saturation tones",
    negativePrompt: "warm orange palette, oversaturated colors",
    tags: ["冷色", "藍調", "夜色"],
    notes: "讓整體配色獨立於光源與場景，可作為色彩控制層。",
  },
  {
    id: "seed-camera-selfie-arm-length",
    category: "鏡頭角度",
    title: "自拍臂距視角",
    subtitle: "近距離手機自拍角度",
    previewImagePath: "/api/uploads/seed/mirror-selfie-pose.png",
    prompt: "selfie arm-length camera angle, close casual phone perspective, slight handheld distortion",
    negativePrompt: "distant telephoto angle, studio tripod perspective",
    tags: ["自拍", "角度", "手機"],
    notes: "用於控制鏡頭位置，和鏡頭質感分離。",
  },
  {
    id: "seed-composition-centered",
    category: "構圖規則",
    title: "中心構圖",
    subtitle: "主體置中且視線穩定",
    previewImagePath: "/api/uploads/seed/half-body-framing.png",
    prompt: "center composition, subject placed in the middle, balanced negative space",
    negativePrompt: "unbalanced crop, accidental off-center framing",
    tags: ["構圖", "置中", "穩定"],
    notes: "適合封面、人像與需要穩定視覺焦點的畫面。",
  },
  {
    id: "seed-material-lace",
    category: "材質",
    title: "蕾絲細節",
    subtitle: "柔軟透明的服裝紋理",
    previewImagePath: "/api/uploads/seed/cropped-knit-cardigan.png",
    prompt: "delicate lace fabric detail, semi-transparent textile texture, soft intricate pattern",
    negativePrompt: "plastic fabric, muddy texture, noisy pattern",
    tags: ["蕾絲", "材質", "紋理"],
    notes: "可用於上裝、配飾或版式質感的細節加強。",
  },
  {
    id: "seed-text-japanese-small-type",
    category: "文本元素",
    title: "日文小字",
    subtitle: "低調雜誌感文字點綴",
    previewImagePath: "/api/uploads/seed/scrapbook-sticker-layout.png",
    prompt: "small Japanese text accents, subtle editorial typography, clean readable tiny captions",
    negativePrompt: "garbled text, huge title text, messy typography",
    tags: ["文字", "日文", "排版"],
    notes: "只控制畫面文字元素，不等同於整體版式。",
  },
  {
    id: "seed-platform-xiaohongshu-cover",
    category: "平台媒介",
    title: "小紅書封面",
    subtitle: "社群封面式直向內容",
    previewImagePath: "/api/uploads/seed/sns-smartphone-snapshot.png",
    prompt: "Xiaohongshu cover style, social media cover image, polished lifestyle thumbnail layout",
    negativePrompt: "desktop website layout, cluttered ad banner",
    tags: ["小紅書", "封面", "社群"],
    notes: "指定最終媒介外觀，可搭配版式設計與文本元素。",
  },
  {
    id: "seed-realism-natural-skin",
    category: "真實性 / 缺陷控制",
    title: "不要 AI 塑膠皮膚",
    subtitle: "保留自然皮膚紋理與微瑕疵",
    previewImagePath: "/api/uploads/seed/sns-smartphone-snapshot.png",
    prompt: "natural skin texture, slight pores, realistic imperfect human skin, not plastic-looking",
    negativePrompt: "AI plastic skin, waxy skin, over-smoothed face",
    priority: "core",
    lockPolicy: "cannot_override",
    tags: ["真實", "皮膚", "缺陷控制"],
    notes: "用於提升真實感並避免過度磨皮。",
  },
  {
    id: "seed-post-low-res-compression",
    category: "後期處理",
    title: "低解析壓縮",
    subtitle: "社群平台壓縮後的後製感",
    previewImagePath: "/api/uploads/seed/subtle-film-grain-overlay.png",
    prompt: "subtle low-resolution social media compression, slight digital softness, compressed snapshot feel",
    negativePrompt: "severe artifacting, unreadable image, broken pixels",
    tags: ["後期", "壓縮", "社群"],
    notes: "適合製造私人快照或平台轉存的後製質感。",
  },
  {
    id: "seed-negative-bad-hands",
    category: "Negative Atom",
    title: "不要錯誤手指",
    subtitle: "排除多指與手部融合",
    previewImagePath: "/api/uploads/seed/phone-in-hand.png",
    prompt: "extra fingers, malformed hands, fused fingers, broken hand anatomy",
    negativePrompt: "",
    priority: "core",
    lockPolicy: "cannot_override",
    tags: ["負面", "手指", "結構"],
    notes: "Negative Atom 會進入 Negative Prompt，不加入正向 Prompt。",
  },
  {
    id: "seed-size-vertical-story",
    category: "尺寸",
    title: "9:16 手機直圖",
    subtitle: "適合限時動態與短影音封面",
    previewImagePath: "/api/uploads/seed/sns-smartphone-snapshot.png",
    prompt: "vertical 9:16 mobile image aspect ratio",
    negativePrompt: "horizontal landscape crop",
    tags: ["尺寸", "直圖", "手機"],
    notes: "只有需要明確輸出比例時才加入組合。",
  },
  {
    id: "seed-quality-high",
    category: "質量",
    title: "高質量輸出",
    subtitle: "清晰乾淨的生成品質控制",
    previewImagePath: "/api/uploads/seed/soft-cinematic-young-woman-portrait-base.png",
    prompt: "high quality output, clean details, sharp but natural image rendering",
    negativePrompt: "low quality, blurry, distorted details",
    tags: ["質量", "清晰", "高品質"],
    notes: "只有原始需求明確要求品質控制時才使用。",
  },
];
